name: Node.js CI - with cache

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    name: run build process
    uses: TrustAfrica/GHA.workflows/.github/workflows/gha.workflows.build-node.yml@main

  deploy-job:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-app
          path: downloaded-content 
      - run: geekyeggo/delete-artifact@v2  # This will delete the artifact at the end of the action run, so it won't be accessible and will only temporarily use the storage available to your account.
        with:
          name: my-app   
