name: Node.js CI - with cache

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    name: run build process
    uses: TrustAfrica/GHA.workflows/.github/workflows/gha.workflows.build-node.yml@main

  deploy-job:
    needs: [ ci ]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: my-app
          path: downloaded-content

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: my-app
